### ISSUE TITLE
Update Crates.io

### ISSUE THREAD

**Issue by caemor** [lholden/job_scheduler#19]
Hello,
thanks for your scheduler. Could you please update this crate on crates.io so I can switch back to using it from there instead of from git. 
Thanks in Advance,
Chris

**Comment by lholden** [comment]
Ah! I'm sorry for not getting that out sooner. I'll push a release out today!

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by caemor** [comment]
Thanks for the super quick response :-)

**Comment by lholden** [comment]
Published :)
