### ISSUE TITLE
Please update cron

### ISSUE THREAD

**Issue by TheUberCatman** [lholden/job_scheduler#2]
the cron lib you are using '0.2.0' has some problems with the most recent version of rust. can you update to the newer version?

**Comment by uncode** [comment]
@lholden please!

**Comment by TheUberCatman** [comment]
Because the dev is not responding I decided to make my own library. you can find it here: https://crates.io/crates/cronjob

**Comment by lholden** [comment]
I'm sorry for getting around to this late. This has been updated now.
