### ISSUE TITLE
* 0/2 * * * * * every two minutes seems to run every second

### ISSUE THREAD

**Issue by glennpierce** [lholden/job_scheduler#6]
I can't seem to get a task to run every two minutes. What am I doing wrong ?

Thanks

extern crate chrono;
extern crate crossbeam;
extern crate liblasso;

use std::time::Duration;
use liblasso::job_scheduler::*;
use std::{thread, time};
use chrono::*;

#[test]
fn schedule_simple() {

    let mut sched = JobScheduler::new();

    sched.add(Job::new("* 0/2 * * * * *".parse().unwrap(), move || {
        println!("{}: Hello World (every 2 minutes)!", Utc::now());
    }));

    loop {
        sched.tick();
        //sched.tick_async();

        std::thread::sleep(Duration::from_millis(500));
    }
}

**Comment by lholden** [comment]
@glennpierce Hi there! I believe the way you have your cron scheduled is that it will run every second for a minute every 2 minutes?

If you change that to 
"0 0/2 * * * * *" it will run once at the start of the minute every two minutes.
